/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ApprovedChannelInfo implements org.apache.thrift.TBase<ApprovedChannelInfo, ApprovedChannelInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ApprovedChannelInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ApprovedChannelInfo");

  private static final org.apache.thrift.protocol.TField CHANNEL_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("channelInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField APPROVED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("approvedAt", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ApprovedChannelInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ApprovedChannelInfoTupleSchemeFactory());
  }

  public ChannelInfo channelInfo; // required
  public long approvedAt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CHANNEL_INFO((short)1, "channelInfo"),
    APPROVED_AT((short)2, "approvedAt");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CHANNEL_INFO
          return CHANNEL_INFO;
        case 2: // APPROVED_AT
          return APPROVED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __APPROVEDAT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CHANNEL_INFO, new org.apache.thrift.meta_data.FieldMetaData("channelInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ChannelInfo.class)));
    tmpMap.put(_Fields.APPROVED_AT, new org.apache.thrift.meta_data.FieldMetaData("approvedAt", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ApprovedChannelInfo.class, metaDataMap);
  }

  public ApprovedChannelInfo() {
  }

  public ApprovedChannelInfo(
    ChannelInfo channelInfo,
    long approvedAt)
  {
    this();
    this.channelInfo = channelInfo;
    this.approvedAt = approvedAt;
    setApprovedAtIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ApprovedChannelInfo(ApprovedChannelInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetChannelInfo()) {
      this.channelInfo = new ChannelInfo(other.channelInfo);
    }
    this.approvedAt = other.approvedAt;
  }

  public ApprovedChannelInfo deepCopy() {
    return new ApprovedChannelInfo(this);
  }

  @Override
  public void clear() {
    this.channelInfo = null;
    setApprovedAtIsSet(false);
    this.approvedAt = 0;
  }

  public ChannelInfo getChannelInfo() {
    return this.channelInfo;
  }

  public ApprovedChannelInfo setChannelInfo(ChannelInfo channelInfo) {
    this.channelInfo = channelInfo;
    return this;
  }

  public void unsetChannelInfo() {
    this.channelInfo = null;
  }

  /** Returns true if field channelInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetChannelInfo() {
    return this.channelInfo != null;
  }

  public void setChannelInfoIsSet(boolean value) {
    if (!value) {
      this.channelInfo = null;
    }
  }

  public long getApprovedAt() {
    return this.approvedAt;
  }

  public ApprovedChannelInfo setApprovedAt(long approvedAt) {
    this.approvedAt = approvedAt;
    setApprovedAtIsSet(true);
    return this;
  }

  public void unsetApprovedAt() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __APPROVEDAT_ISSET_ID);
  }

  /** Returns true if field approvedAt is set (has been assigned a value) and false otherwise */
  public boolean isSetApprovedAt() {
    return EncodingUtils.testBit(__isset_bitfield, __APPROVEDAT_ISSET_ID);
  }

  public void setApprovedAtIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __APPROVEDAT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CHANNEL_INFO:
      if (value == null) {
        unsetChannelInfo();
      } else {
        setChannelInfo((ChannelInfo)value);
      }
      break;

    case APPROVED_AT:
      if (value == null) {
        unsetApprovedAt();
      } else {
        setApprovedAt((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CHANNEL_INFO:
      return getChannelInfo();

    case APPROVED_AT:
      return Long.valueOf(getApprovedAt());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CHANNEL_INFO:
      return isSetChannelInfo();
    case APPROVED_AT:
      return isSetApprovedAt();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ApprovedChannelInfo)
      return this.equals((ApprovedChannelInfo)that);
    return false;
  }

  public boolean equals(ApprovedChannelInfo that) {
    if (that == null)
      return false;

    boolean this_present_channelInfo = true && this.isSetChannelInfo();
    boolean that_present_channelInfo = true && that.isSetChannelInfo();
    if (this_present_channelInfo || that_present_channelInfo) {
      if (!(this_present_channelInfo && that_present_channelInfo))
        return false;
      if (!this.channelInfo.equals(that.channelInfo))
        return false;
    }

    boolean this_present_approvedAt = true;
    boolean that_present_approvedAt = true;
    if (this_present_approvedAt || that_present_approvedAt) {
      if (!(this_present_approvedAt && that_present_approvedAt))
        return false;
      if (this.approvedAt != that.approvedAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ApprovedChannelInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetChannelInfo()).compareTo(other.isSetChannelInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChannelInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.channelInfo, other.channelInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetApprovedAt()).compareTo(other.isSetApprovedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApprovedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.approvedAt, other.approvedAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ApprovedChannelInfo(");
    boolean first = true;

    sb.append("channelInfo:");
    if (this.channelInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.channelInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("approvedAt:");
    sb.append(this.approvedAt);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (channelInfo != null) {
      channelInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ApprovedChannelInfoStandardSchemeFactory implements SchemeFactory {
    public ApprovedChannelInfoStandardScheme getScheme() {
      return new ApprovedChannelInfoStandardScheme();
    }
  }

  private static class ApprovedChannelInfoStandardScheme extends StandardScheme<ApprovedChannelInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ApprovedChannelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CHANNEL_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.channelInfo = new ChannelInfo();
              struct.channelInfo.read(iprot);
              struct.setChannelInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // APPROVED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.approvedAt = iprot.readI64();
              struct.setApprovedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ApprovedChannelInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.channelInfo != null) {
        oprot.writeFieldBegin(CHANNEL_INFO_FIELD_DESC);
        struct.channelInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(APPROVED_AT_FIELD_DESC);
      oprot.writeI64(struct.approvedAt);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ApprovedChannelInfoTupleSchemeFactory implements SchemeFactory {
    public ApprovedChannelInfoTupleScheme getScheme() {
      return new ApprovedChannelInfoTupleScheme();
    }
  }

  private static class ApprovedChannelInfoTupleScheme extends TupleScheme<ApprovedChannelInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ApprovedChannelInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetChannelInfo()) {
        optionals.set(0);
      }
      if (struct.isSetApprovedAt()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetChannelInfo()) {
        struct.channelInfo.write(oprot);
      }
      if (struct.isSetApprovedAt()) {
        oprot.writeI64(struct.approvedAt);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ApprovedChannelInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.channelInfo = new ChannelInfo();
        struct.channelInfo.read(iprot);
        struct.setChannelInfoIsSet(true);
      }
      if (incoming.get(1)) {
        struct.approvedAt = iprot.readI64();
        struct.setApprovedAtIsSet(true);
      }
    }
  }

}

