/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SnsFriend implements org.apache.thrift.TBase<SnsFriend, SnsFriend._Fields>, java.io.Serializable, Cloneable, Comparable<SnsFriend> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SnsFriend");

  private static final org.apache.thrift.protocol.TField SNS_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("snsUserId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SNS_USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("snsUserName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SNS_ID_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("snsIdType", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SnsFriendStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SnsFriendTupleSchemeFactory());
  }

  public String snsUserId; // required
  public String snsUserName; // required
  /**
   * 
   * @see SnsIdType
   */
  public SnsIdType snsIdType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SNS_USER_ID((short)1, "snsUserId"),
    SNS_USER_NAME((short)2, "snsUserName"),
    /**
     * 
     * @see SnsIdType
     */
    SNS_ID_TYPE((short)3, "snsIdType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SNS_USER_ID
          return SNS_USER_ID;
        case 2: // SNS_USER_NAME
          return SNS_USER_NAME;
        case 3: // SNS_ID_TYPE
          return SNS_ID_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SNS_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("snsUserId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SNS_USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("snsUserName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SNS_ID_TYPE, new org.apache.thrift.meta_data.FieldMetaData("snsIdType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, SnsIdType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SnsFriend.class, metaDataMap);
  }

  public SnsFriend() {
  }

  public SnsFriend(
    String snsUserId,
    String snsUserName,
    SnsIdType snsIdType)
  {
    this();
    this.snsUserId = snsUserId;
    this.snsUserName = snsUserName;
    this.snsIdType = snsIdType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SnsFriend(SnsFriend other) {
    if (other.isSetSnsUserId()) {
      this.snsUserId = other.snsUserId;
    }
    if (other.isSetSnsUserName()) {
      this.snsUserName = other.snsUserName;
    }
    if (other.isSetSnsIdType()) {
      this.snsIdType = other.snsIdType;
    }
  }

  public SnsFriend deepCopy() {
    return new SnsFriend(this);
  }

  @Override
  public void clear() {
    this.snsUserId = null;
    this.snsUserName = null;
    this.snsIdType = null;
  }

  public String getSnsUserId() {
    return this.snsUserId;
  }

  public SnsFriend setSnsUserId(String snsUserId) {
    this.snsUserId = snsUserId;
    return this;
  }

  public void unsetSnsUserId() {
    this.snsUserId = null;
  }

  /** Returns true if field snsUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetSnsUserId() {
    return this.snsUserId != null;
  }

  public void setSnsUserIdIsSet(boolean value) {
    if (!value) {
      this.snsUserId = null;
    }
  }

  public String getSnsUserName() {
    return this.snsUserName;
  }

  public SnsFriend setSnsUserName(String snsUserName) {
    this.snsUserName = snsUserName;
    return this;
  }

  public void unsetSnsUserName() {
    this.snsUserName = null;
  }

  /** Returns true if field snsUserName is set (has been assigned a value) and false otherwise */
  public boolean isSetSnsUserName() {
    return this.snsUserName != null;
  }

  public void setSnsUserNameIsSet(boolean value) {
    if (!value) {
      this.snsUserName = null;
    }
  }

  /**
   * 
   * @see SnsIdType
   */
  public SnsIdType getSnsIdType() {
    return this.snsIdType;
  }

  /**
   * 
   * @see SnsIdType
   */
  public SnsFriend setSnsIdType(SnsIdType snsIdType) {
    this.snsIdType = snsIdType;
    return this;
  }

  public void unsetSnsIdType() {
    this.snsIdType = null;
  }

  /** Returns true if field snsIdType is set (has been assigned a value) and false otherwise */
  public boolean isSetSnsIdType() {
    return this.snsIdType != null;
  }

  public void setSnsIdTypeIsSet(boolean value) {
    if (!value) {
      this.snsIdType = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SNS_USER_ID:
      if (value == null) {
        unsetSnsUserId();
      } else {
        setSnsUserId((String)value);
      }
      break;

    case SNS_USER_NAME:
      if (value == null) {
        unsetSnsUserName();
      } else {
        setSnsUserName((String)value);
      }
      break;

    case SNS_ID_TYPE:
      if (value == null) {
        unsetSnsIdType();
      } else {
        setSnsIdType((SnsIdType)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SNS_USER_ID:
      return getSnsUserId();

    case SNS_USER_NAME:
      return getSnsUserName();

    case SNS_ID_TYPE:
      return getSnsIdType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SNS_USER_ID:
      return isSetSnsUserId();
    case SNS_USER_NAME:
      return isSetSnsUserName();
    case SNS_ID_TYPE:
      return isSetSnsIdType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SnsFriend)
      return this.equals((SnsFriend)that);
    return false;
  }

  public boolean equals(SnsFriend that) {
    if (that == null)
      return false;

    boolean this_present_snsUserId = true && this.isSetSnsUserId();
    boolean that_present_snsUserId = true && that.isSetSnsUserId();
    if (this_present_snsUserId || that_present_snsUserId) {
      if (!(this_present_snsUserId && that_present_snsUserId))
        return false;
      if (!this.snsUserId.equals(that.snsUserId))
        return false;
    }

    boolean this_present_snsUserName = true && this.isSetSnsUserName();
    boolean that_present_snsUserName = true && that.isSetSnsUserName();
    if (this_present_snsUserName || that_present_snsUserName) {
      if (!(this_present_snsUserName && that_present_snsUserName))
        return false;
      if (!this.snsUserName.equals(that.snsUserName))
        return false;
    }

    boolean this_present_snsIdType = true && this.isSetSnsIdType();
    boolean that_present_snsIdType = true && that.isSetSnsIdType();
    if (this_present_snsIdType || that_present_snsIdType) {
      if (!(this_present_snsIdType && that_present_snsIdType))
        return false;
      if (!this.snsIdType.equals(that.snsIdType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SnsFriend other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSnsUserId()).compareTo(other.isSetSnsUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSnsUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.snsUserId, other.snsUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSnsUserName()).compareTo(other.isSetSnsUserName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSnsUserName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.snsUserName, other.snsUserName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSnsIdType()).compareTo(other.isSetSnsIdType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSnsIdType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.snsIdType, other.snsIdType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SnsFriend(");
    boolean first = true;

    sb.append("snsUserId:");
    if (this.snsUserId == null) {
      sb.append("null");
    } else {
      sb.append(this.snsUserId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("snsUserName:");
    if (this.snsUserName == null) {
      sb.append("null");
    } else {
      sb.append(this.snsUserName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("snsIdType:");
    if (this.snsIdType == null) {
      sb.append("null");
    } else {
      sb.append(this.snsIdType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SnsFriendStandardSchemeFactory implements SchemeFactory {
    public SnsFriendStandardScheme getScheme() {
      return new SnsFriendStandardScheme();
    }
  }

  private static class SnsFriendStandardScheme extends StandardScheme<SnsFriend> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SnsFriend struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SNS_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.snsUserId = iprot.readString();
              struct.setSnsUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SNS_USER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.snsUserName = iprot.readString();
              struct.setSnsUserNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SNS_ID_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.snsIdType = SnsIdType.findByValue(iprot.readI32());
              struct.setSnsIdTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SnsFriend struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.snsUserId != null) {
        oprot.writeFieldBegin(SNS_USER_ID_FIELD_DESC);
        oprot.writeString(struct.snsUserId);
        oprot.writeFieldEnd();
      }
      if (struct.snsUserName != null) {
        oprot.writeFieldBegin(SNS_USER_NAME_FIELD_DESC);
        oprot.writeString(struct.snsUserName);
        oprot.writeFieldEnd();
      }
      if (struct.snsIdType != null) {
        oprot.writeFieldBegin(SNS_ID_TYPE_FIELD_DESC);
        oprot.writeI32(struct.snsIdType.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SnsFriendTupleSchemeFactory implements SchemeFactory {
    public SnsFriendTupleScheme getScheme() {
      return new SnsFriendTupleScheme();
    }
  }

  private static class SnsFriendTupleScheme extends TupleScheme<SnsFriend> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SnsFriend struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSnsUserId()) {
        optionals.set(0);
      }
      if (struct.isSetSnsUserName()) {
        optionals.set(1);
      }
      if (struct.isSetSnsIdType()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetSnsUserId()) {
        oprot.writeString(struct.snsUserId);
      }
      if (struct.isSetSnsUserName()) {
        oprot.writeString(struct.snsUserName);
      }
      if (struct.isSetSnsIdType()) {
        oprot.writeI32(struct.snsIdType.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SnsFriend struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.snsUserId = iprot.readString();
        struct.setSnsUserIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.snsUserName = iprot.readString();
        struct.setSnsUserNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.snsIdType = SnsIdType.findByValue(iprot.readI32());
        struct.setSnsIdTypeIsSet(true);
      }
    }
  }

}

