/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SquareFeature implements org.apache.thrift.TBase<SquareFeature, SquareFeature._Fields>, java.io.Serializable, Cloneable, Comparable<SquareFeature> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SquareFeature");

  private static final org.apache.thrift.protocol.TField CONTROL_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("controlState", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BOOLEAN_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("booleanValue", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SquareFeatureStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SquareFeatureTupleSchemeFactory());
  }

  /**
   * 
   * @see SquareFeatureControlState
   */
  public SquareFeatureControlState controlState; // required
  /**
   * 
   * @see BooleanState
   */
  public BooleanState booleanValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see SquareFeatureControlState
     */
    CONTROL_STATE((short)1, "controlState"),
    /**
     * 
     * @see BooleanState
     */
    BOOLEAN_VALUE((short)2, "booleanValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONTROL_STATE
          return CONTROL_STATE;
        case 2: // BOOLEAN_VALUE
          return BOOLEAN_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONTROL_STATE, new org.apache.thrift.meta_data.FieldMetaData("controlState", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, SquareFeatureControlState.class)));
    tmpMap.put(_Fields.BOOLEAN_VALUE, new org.apache.thrift.meta_data.FieldMetaData("booleanValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, BooleanState.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SquareFeature.class, metaDataMap);
  }

  public SquareFeature() {
  }

  public SquareFeature(
    SquareFeatureControlState controlState,
    BooleanState booleanValue)
  {
    this();
    this.controlState = controlState;
    this.booleanValue = booleanValue;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SquareFeature(SquareFeature other) {
    if (other.isSetControlState()) {
      this.controlState = other.controlState;
    }
    if (other.isSetBooleanValue()) {
      this.booleanValue = other.booleanValue;
    }
  }

  public SquareFeature deepCopy() {
    return new SquareFeature(this);
  }

  @Override
  public void clear() {
    this.controlState = null;
    this.booleanValue = null;
  }

  /**
   * 
   * @see SquareFeatureControlState
   */
  public SquareFeatureControlState getControlState() {
    return this.controlState;
  }

  /**
   * 
   * @see SquareFeatureControlState
   */
  public SquareFeature setControlState(SquareFeatureControlState controlState) {
    this.controlState = controlState;
    return this;
  }

  public void unsetControlState() {
    this.controlState = null;
  }

  /** Returns true if field controlState is set (has been assigned a value) and false otherwise */
  public boolean isSetControlState() {
    return this.controlState != null;
  }

  public void setControlStateIsSet(boolean value) {
    if (!value) {
      this.controlState = null;
    }
  }

  /**
   * 
   * @see BooleanState
   */
  public BooleanState getBooleanValue() {
    return this.booleanValue;
  }

  /**
   * 
   * @see BooleanState
   */
  public SquareFeature setBooleanValue(BooleanState booleanValue) {
    this.booleanValue = booleanValue;
    return this;
  }

  public void unsetBooleanValue() {
    this.booleanValue = null;
  }

  /** Returns true if field booleanValue is set (has been assigned a value) and false otherwise */
  public boolean isSetBooleanValue() {
    return this.booleanValue != null;
  }

  public void setBooleanValueIsSet(boolean value) {
    if (!value) {
      this.booleanValue = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CONTROL_STATE:
      if (value == null) {
        unsetControlState();
      } else {
        setControlState((SquareFeatureControlState)value);
      }
      break;

    case BOOLEAN_VALUE:
      if (value == null) {
        unsetBooleanValue();
      } else {
        setBooleanValue((BooleanState)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CONTROL_STATE:
      return getControlState();

    case BOOLEAN_VALUE:
      return getBooleanValue();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CONTROL_STATE:
      return isSetControlState();
    case BOOLEAN_VALUE:
      return isSetBooleanValue();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SquareFeature)
      return this.equals((SquareFeature)that);
    return false;
  }

  public boolean equals(SquareFeature that) {
    if (that == null)
      return false;

    boolean this_present_controlState = true && this.isSetControlState();
    boolean that_present_controlState = true && that.isSetControlState();
    if (this_present_controlState || that_present_controlState) {
      if (!(this_present_controlState && that_present_controlState))
        return false;
      if (!this.controlState.equals(that.controlState))
        return false;
    }

    boolean this_present_booleanValue = true && this.isSetBooleanValue();
    boolean that_present_booleanValue = true && that.isSetBooleanValue();
    if (this_present_booleanValue || that_present_booleanValue) {
      if (!(this_present_booleanValue && that_present_booleanValue))
        return false;
      if (!this.booleanValue.equals(that.booleanValue))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SquareFeature other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetControlState()).compareTo(other.isSetControlState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetControlState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.controlState, other.controlState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBooleanValue()).compareTo(other.isSetBooleanValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBooleanValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.booleanValue, other.booleanValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SquareFeature(");
    boolean first = true;

    sb.append("controlState:");
    if (this.controlState == null) {
      sb.append("null");
    } else {
      sb.append(this.controlState);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("booleanValue:");
    if (this.booleanValue == null) {
      sb.append("null");
    } else {
      sb.append(this.booleanValue);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SquareFeatureStandardSchemeFactory implements SchemeFactory {
    public SquareFeatureStandardScheme getScheme() {
      return new SquareFeatureStandardScheme();
    }
  }

  private static class SquareFeatureStandardScheme extends StandardScheme<SquareFeature> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SquareFeature struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONTROL_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.controlState = SquareFeatureControlState.findByValue(iprot.readI32());
              struct.setControlStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BOOLEAN_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.booleanValue = BooleanState.findByValue(iprot.readI32());
              struct.setBooleanValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SquareFeature struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.controlState != null) {
        oprot.writeFieldBegin(CONTROL_STATE_FIELD_DESC);
        oprot.writeI32(struct.controlState.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.booleanValue != null) {
        oprot.writeFieldBegin(BOOLEAN_VALUE_FIELD_DESC);
        oprot.writeI32(struct.booleanValue.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SquareFeatureTupleSchemeFactory implements SchemeFactory {
    public SquareFeatureTupleScheme getScheme() {
      return new SquareFeatureTupleScheme();
    }
  }

  private static class SquareFeatureTupleScheme extends TupleScheme<SquareFeature> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SquareFeature struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetControlState()) {
        optionals.set(0);
      }
      if (struct.isSetBooleanValue()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetControlState()) {
        oprot.writeI32(struct.controlState.getValue());
      }
      if (struct.isSetBooleanValue()) {
        oprot.writeI32(struct.booleanValue.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SquareFeature struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.controlState = SquareFeatureControlState.findByValue(iprot.readI32());
        struct.setControlStateIsSet(true);
      }
      if (incoming.get(1)) {
        struct.booleanValue = BooleanState.findByValue(iprot.readI32());
        struct.setBooleanValueIsSet(true);
      }
    }
  }

}

