/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SquarePreference implements org.apache.thrift.TBase<SquarePreference, SquarePreference._Fields>, java.io.Serializable, Cloneable, Comparable<SquarePreference> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SquarePreference");

  private static final org.apache.thrift.protocol.TField FAVORITE_TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("favoriteTimestamp", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NOTI_FOR_NEW_JOIN_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("notiForNewJoinRequest", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SquarePreferenceStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SquarePreferenceTupleSchemeFactory());
  }

  public long favoriteTimestamp; // required
  public boolean notiForNewJoinRequest; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FAVORITE_TIMESTAMP((short)1, "favoriteTimestamp"),
    NOTI_FOR_NEW_JOIN_REQUEST((short)2, "notiForNewJoinRequest");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FAVORITE_TIMESTAMP
          return FAVORITE_TIMESTAMP;
        case 2: // NOTI_FOR_NEW_JOIN_REQUEST
          return NOTI_FOR_NEW_JOIN_REQUEST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FAVORITETIMESTAMP_ISSET_ID = 0;
  private static final int __NOTIFORNEWJOINREQUEST_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FAVORITE_TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("favoriteTimestamp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NOTI_FOR_NEW_JOIN_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("notiForNewJoinRequest", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SquarePreference.class, metaDataMap);
  }

  public SquarePreference() {
  }

  public SquarePreference(
    long favoriteTimestamp,
    boolean notiForNewJoinRequest)
  {
    this();
    this.favoriteTimestamp = favoriteTimestamp;
    setFavoriteTimestampIsSet(true);
    this.notiForNewJoinRequest = notiForNewJoinRequest;
    setNotiForNewJoinRequestIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SquarePreference(SquarePreference other) {
    __isset_bitfield = other.__isset_bitfield;
    this.favoriteTimestamp = other.favoriteTimestamp;
    this.notiForNewJoinRequest = other.notiForNewJoinRequest;
  }

  public SquarePreference deepCopy() {
    return new SquarePreference(this);
  }

  @Override
  public void clear() {
    setFavoriteTimestampIsSet(false);
    this.favoriteTimestamp = 0;
    setNotiForNewJoinRequestIsSet(false);
    this.notiForNewJoinRequest = false;
  }

  public long getFavoriteTimestamp() {
    return this.favoriteTimestamp;
  }

  public SquarePreference setFavoriteTimestamp(long favoriteTimestamp) {
    this.favoriteTimestamp = favoriteTimestamp;
    setFavoriteTimestampIsSet(true);
    return this;
  }

  public void unsetFavoriteTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FAVORITETIMESTAMP_ISSET_ID);
  }

  /** Returns true if field favoriteTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetFavoriteTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __FAVORITETIMESTAMP_ISSET_ID);
  }

  public void setFavoriteTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FAVORITETIMESTAMP_ISSET_ID, value);
  }

  public boolean isNotiForNewJoinRequest() {
    return this.notiForNewJoinRequest;
  }

  public SquarePreference setNotiForNewJoinRequest(boolean notiForNewJoinRequest) {
    this.notiForNewJoinRequest = notiForNewJoinRequest;
    setNotiForNewJoinRequestIsSet(true);
    return this;
  }

  public void unsetNotiForNewJoinRequest() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NOTIFORNEWJOINREQUEST_ISSET_ID);
  }

  /** Returns true if field notiForNewJoinRequest is set (has been assigned a value) and false otherwise */
  public boolean isSetNotiForNewJoinRequest() {
    return EncodingUtils.testBit(__isset_bitfield, __NOTIFORNEWJOINREQUEST_ISSET_ID);
  }

  public void setNotiForNewJoinRequestIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NOTIFORNEWJOINREQUEST_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FAVORITE_TIMESTAMP:
      if (value == null) {
        unsetFavoriteTimestamp();
      } else {
        setFavoriteTimestamp((Long)value);
      }
      break;

    case NOTI_FOR_NEW_JOIN_REQUEST:
      if (value == null) {
        unsetNotiForNewJoinRequest();
      } else {
        setNotiForNewJoinRequest((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FAVORITE_TIMESTAMP:
      return Long.valueOf(getFavoriteTimestamp());

    case NOTI_FOR_NEW_JOIN_REQUEST:
      return Boolean.valueOf(isNotiForNewJoinRequest());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FAVORITE_TIMESTAMP:
      return isSetFavoriteTimestamp();
    case NOTI_FOR_NEW_JOIN_REQUEST:
      return isSetNotiForNewJoinRequest();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SquarePreference)
      return this.equals((SquarePreference)that);
    return false;
  }

  public boolean equals(SquarePreference that) {
    if (that == null)
      return false;

    boolean this_present_favoriteTimestamp = true;
    boolean that_present_favoriteTimestamp = true;
    if (this_present_favoriteTimestamp || that_present_favoriteTimestamp) {
      if (!(this_present_favoriteTimestamp && that_present_favoriteTimestamp))
        return false;
      if (this.favoriteTimestamp != that.favoriteTimestamp)
        return false;
    }

    boolean this_present_notiForNewJoinRequest = true;
    boolean that_present_notiForNewJoinRequest = true;
    if (this_present_notiForNewJoinRequest || that_present_notiForNewJoinRequest) {
      if (!(this_present_notiForNewJoinRequest && that_present_notiForNewJoinRequest))
        return false;
      if (this.notiForNewJoinRequest != that.notiForNewJoinRequest)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SquarePreference other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFavoriteTimestamp()).compareTo(other.isSetFavoriteTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFavoriteTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.favoriteTimestamp, other.favoriteTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNotiForNewJoinRequest()).compareTo(other.isSetNotiForNewJoinRequest());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNotiForNewJoinRequest()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.notiForNewJoinRequest, other.notiForNewJoinRequest);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SquarePreference(");
    boolean first = true;

    sb.append("favoriteTimestamp:");
    sb.append(this.favoriteTimestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("notiForNewJoinRequest:");
    sb.append(this.notiForNewJoinRequest);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SquarePreferenceStandardSchemeFactory implements SchemeFactory {
    public SquarePreferenceStandardScheme getScheme() {
      return new SquarePreferenceStandardScheme();
    }
  }

  private static class SquarePreferenceStandardScheme extends StandardScheme<SquarePreference> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SquarePreference struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FAVORITE_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.favoriteTimestamp = iprot.readI64();
              struct.setFavoriteTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NOTI_FOR_NEW_JOIN_REQUEST
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.notiForNewJoinRequest = iprot.readBool();
              struct.setNotiForNewJoinRequestIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SquarePreference struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(FAVORITE_TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.favoriteTimestamp);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NOTI_FOR_NEW_JOIN_REQUEST_FIELD_DESC);
      oprot.writeBool(struct.notiForNewJoinRequest);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SquarePreferenceTupleSchemeFactory implements SchemeFactory {
    public SquarePreferenceTupleScheme getScheme() {
      return new SquarePreferenceTupleScheme();
    }
  }

  private static class SquarePreferenceTupleScheme extends TupleScheme<SquarePreference> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SquarePreference struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFavoriteTimestamp()) {
        optionals.set(0);
      }
      if (struct.isSetNotiForNewJoinRequest()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetFavoriteTimestamp()) {
        oprot.writeI64(struct.favoriteTimestamp);
      }
      if (struct.isSetNotiForNewJoinRequest()) {
        oprot.writeBool(struct.notiForNewJoinRequest);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SquarePreference struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.favoriteTimestamp = iprot.readI64();
        struct.setFavoriteTimestampIsSet(true);
      }
      if (incoming.get(1)) {
        struct.notiForNewJoinRequest = iprot.readBool();
        struct.setNotiForNewJoinRequestIsSet(true);
      }
    }
  }

}

